### ISSUE TITLE
Problemas no guia de instalação

### ISSUE THREAD

**Issue by felipe-dachshund** [GrupoTuring/workshop_estatistica_com_R#6]
O guia de instalação [instalacao-jupyter-notebook-r.md](https://github.com/GrupoTuring/workshop_estatistica_com_R/blob/master/instalacao-jupyter-notebook-r.md) tem alguns problemas na parte do Linux. O código da seção [B.2](https://github.com/GrupoTuring/workshop_estatistica_com_R/blob/master/instalacao-jupyter-notebook-r.md#b2---instale-o-anaconda) baixa o executável do Windows, em vez do script shell para Linux. Tem q trocar cada uma das duas ocorrências de `Anaconda3-2020.02-Windows-x86_64.exe` por `Anaconda3-2020.02-Linux-x86_64.sh`.

Outra coisa: por default, o anaconda faz o terminal ser iniciado sempre no ambiente `base` depois de instalado. Provavelmente o usuário de Linux não quer isso (eu, pelo menos, não quis), pois fica um incômodo `(base)` no início de cada linha de prompt sempre que o usuário abre o terminal, além de que (talvez?) possa haver alguns resultados inesperados ao se trabalhar com um ambiente anaconda ativado quando o usuário não quer trabalhar com o anaconda. Se não me falha a memória, existem duas formas de mudar isso:

1. Acho que na própria instalação do Anaconda. No fim, ele pergunta se quer que mantenha o `base` ativado por padrão ou não. Tem que escolher a outra resposta, que eu não lembro qual é. Quer dizer, tem q testar instalando num Linux. (Eu não quero ter que desinstalar no meu pra instalar de novo, tenho medo de perder a configuração.)
2. Reconfigurando o Anaconda:
```
conda config --set auto_activate_base False
```

Também acho que valeria a pena mostrar como criar um _launcher_ para o Anaconda Navigator, assim não precisa entrar no terminal só pra executar o Anaconda Navigator. Eu fiz pra mim, é um jeito que funciona pra qualquer GUI compatível com [https://www.freedesktop.org/](freedesktop.org) ou XDG, i.e., que se baseie em X11 (p. ex., Gnome, KDE e Xfce). Basicamente vc cria um arquivo com extensão `.desktop` (p. ex., `anaconda-navigator.desktop`) na pasta `~/.local/share/applications/` com o conteúdo:
```
[Desktop Entry]
Type=Application
Encoding=UTF-8
Name=Anaconda Navigator
GenericName=Anaconda GUI
Comment=GUI to the conda package and environment manager
Comment[pt_BR]=GUI para o gerenciador de pacotes e ambientes conda
Exec=/home/user/anaconda3/bin/anaconda-navigator
Categories=Development;Science;Building;IDE;ProjectManagement;PackageManager;ArtificialIntelligence;DataVisualization;
Icon=/home/user/anaconda3/lib/python3.7/site-packages/anaconda_navigator/static/images/anaconda-icon-256x256.png
Terminal=false
```
substituindo o `user` pelo nome de usuário.

**Comment by gaialucas** [comment]
Agradecemos as sugestões e corrigimos o tutorial 😉
